#!/bin/sh

green="\033[0;32m"
brightgreen="\033[1;32m"
colors=($green $brightgreen)

screenlines=$(expr `tput lines` - 1)
screencols=$(expr `tput cols` / 2 - 1)

chars=(ｱ ｲ ｳ ｴ ｵ ｶ ｷ ｸ ｹ ｺ ｻ ｼ ｽ ｾ ｿ ﾀ ﾁ ﾂ ﾃ ﾄ ﾅ ﾆ ﾇ ﾈ ﾉ ﾊ ﾋ ﾌ ﾍ ﾎ ﾏ ﾐ ﾑ ﾒ ﾓ ﾔ ﾕ ﾖ ﾗ ﾘ ﾙ ﾚ ﾛ ﾜ ﾝ)

count=${#chars[@]}
colorcount=${#colors[@]}

trap "tput sgr0; clear; exit" SIGTERM SIGINT

clear
tput cup 0 0
while :
do for i in $(eval echo {1..$screenlines})
    do for i in $(eval echo {1..$screencols})
        do rand=$(($RANDOM%100))
case $rand in
0)
printf "${colors[$RANDOM%$colorcount]}${chars[$RANDOM%$count]} "
;;
1)
printf "  "
;;
*)
printf "\033[2C"
;;
esac
done
printf "\n"

done
tput cup 0 0
done
